{% set name = "pythesint" %}
{% set version = "1.4.6" %}
{% set sha256 = "555a545ec8416cd1c09921ac43cd9845e9d3c71082dd0ebe90fe250cfe6a43f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/nansencenter/py-thesaurus-interface/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pyyaml
    - requests
    - xdg 1.0.5  # [not win]
    - pip
  run:
    - python
    - pyyaml
    - requests
    - xdg 1.0.5  # [not win]

test:
  requires:
    - mock
    - nose
  commands:
    - nosetests pythesint

about:
  home: https://github.com/nansencenter/py-thesaurus-interface
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'An interface to metadata vocabularies for geospatial and other geophysical data'

  description: |
    pythesint provides access to controled vocabularies following
    the standards defined at NASA's Global Change Master Directory (GCMD)
    (http://gcmd.gsfc.nasa.gov) and the NetCDF-CF conventions
    (http://cfconventions.org/), plus possibly others that will be added as
    needs emerge. The standards are mapped in Python dictionaries and saved
    to json-files.
  doc_url: https://github.com/nansencenter/py-thesaurus-interface
  dev_url: https://github.com/nansencenter/py-thesaurus-interface

extra:
  recipe-maintainers:
    - akorosov
    - aleksandervines
