{% set version = "1.4.7" %}
{% set sha256 = "a3ae5f6eff54969989a12dfbec06b91f3546f4b1d571e4f24569597f47505027" %}

package:
  name: pythesint
  version: {{ version }}

source:
  url: https://github.com/nansencenter/py-thesaurus-interface/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  build:
    - pip
    - python
    - pyyaml
    - requests
    - xdg 1.0.5  # [not win]
    - setuptools
  run:
    - python
    - pyyaml
    - requests
    - xdg 1.0.5  # [not win]

test:
  requires:
    - mock
    - nose
  commands:
    - nosetests pythesint

about:
  home: https://github.com/nansencenter/py-thesaurus-interface
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'An interface to metadata vocabularies for geospatial and other geophysical data'

  description: |
    pythesint provides access to controled vocabularies following
    the standards defined at NASA's Global Change Master Directory (GCMD)
    (http://gcmd.gsfc.nasa.gov) and the NetCDF-CF conventions
    (http://cfconventions.org/), plus possibly others that will be added as
    needs emerge. The standards are mapped in Python dictionaries and saved
    to json-files.
  doc_url: https://github.com/nansencenter/py-thesaurus-interface
  dev_url: https://github.com/nansencenter/py-thesaurus-interface

extra:
  recipe-maintainers:
    - akorosov
    - aleksandervines
