appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gBgvdDYQayyAlNeF+lcoUUZWGg6UrNR+EDrB72kAF393kqbWh1pbjiqb9Jhj4WG20nSQAOP8LmT/JYwh56RXRzL+2D/8WryflGywOPVeFF5VaeDl8BBMKc9yDJs3RslYRWFqPIEU0pDNpJXp07LphjURJwDWvZ1PamIu/hj3pnd+XA05U/kxkk0y4CskSldJTNdG6xbv2yGGAdMAAUv35RBDsOoKISfkrd4kma5nhpBbjCkIo9dHBw9IBkrzBdhyy7KcOHtGPAOkbwSsCcK4VJOPloz+8KVIajYU+43f+Wrx3dn9xJgZAAA6Mkbj4oGG3HA4H7Y/ex3ka8WH5KkoeY2rSzgE+TTwQui3De3xyY48APDM1Gfm94FpXe3X7Wh2BCvotM4fgdKTt6GBO8oQmQTNXjoU4dn8qW+xuDwqCnYGiZ5+EDTjqWiUqTB7UFduRUW1M+hoh1rkpEGYWpcmW60oM0V7tUBvtv3P7KepVrMzgZhkKNYRfyzECrvMMN0aFbWGF6SjUukZtHF+iUWBAQSngrjJI4IH5kJAdYIrlGn0Kwx+BLkGT9Zj7aZeoZxDTvXOuV9skfTH/Rj+H45+rGPdThjFK7mGc4q6GpGczQUCcsSAdlIKG9QTBMXVSjIUnsu0lW6bmp8D0GS28WDmaVJGCWMOsNxPRVUwgmlpp18=}
